<?php
use Illuminate\Support\Str;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CustomersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      if(DB::table('customers')->get()->count() == 0){
        DB::table('customers')->insert(
         [
            'fname' => 'Chase',
            'lname' => 'Doe',
            'contact' => '09158547791',
            'facebook' => '/sample',
            'twitter' => '/sample',
            'gplus' => null ,
            'address' => 'Imus,Cavite',
            'email' =>'ChaseDoe@gmail.com',
            'password' => bcrypt('secret'),
            'is_verified' => 1,
            'verification_token' =>null ,
            'remember_token' => str_random(40),
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
          [
            'fname' => 'Case',
            'lname' => 'Doe',
            'contact' => '09158547791',
            'facebook' => '/sample',
            'twitter' => '/sample',
            'gplus' => null ,
            'address' => 'Imus,Cavite',
            'email' =>'CaseDoe@gmail.com',
            'password' => bcrypt('secret'),
            'is_verified' => 1,
            'verification_token' =>null ,
            'remember_token' => str_random(40),
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
          [
            'fname' => 'Claude',
            'lname' => 'Doe',
            'contact' => '09158547791',
            'facebook' => '/sample',
            'twitter' => '/sample',
            'gplus' => null,
            'address' => 'Imus,Cavite',
            'email' =>'ClaudeDoe@gmail.com',
            'password' => bcrypt('secret'),
            'is_verified' => 1,
            'verification_token' =>null ,
            'remember_token' => str_random(40),
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
          [
            'fname' => 'Camilla',
            'lname' => 'Doe',
            'contact' => '09158547791',
            'facebook' => '/sample',
            'twitter' => '/sample',
            'gplus' => null,
            'address' => 'Imus,Cavite',
            'email' =>'CamilleDoe@gmail.com',
            'password' => bcrypt('secret'),
            'is_verified' => 1,
            'verification_token' =>null ,
            'remember_token' => str_random(40),
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
          [
            'fname' => 'Camille',
            'lname' => 'Doe',
            'contact' => '09158547791',
            'facebook' => '/sample',
            'twitter' => '/sample',
            'gplus' => null ,
            'address' => 'Imus,Cavite',
            'email' =>'CamilleaDoe@gmail.com',
            'password' => bcrypt('secret'),
            'is_verified' => 1,
            'verification_token' =>null ,
            'remember_token' => str_random(40),
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
        [
            'fname' => 'Cheyenne',
            'lname' => 'Doe',
            'contact' => '09158547791',
            'facebook' => '/sample',
            'twitter' => '/sample',
            'gplus' => null ,
            'address' => 'Imus,Cavite',
            'email' =>'CheyenneDoe@gmail.com',
            'password' => bcrypt('secret'),
            'is_verified' => 1,
            'verification_token' =>null ,
            'remember_token' => str_random(40),
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
        [
            'fname' => 'Cage',
            'lname' => 'Doe',
            'contact' => '09158547791',
            'facebook' => '/sample',
            'twitter' => '/sample',
            'gplus' => null,
            'address' => 'Imus,Cavite',
            'email' =>'CageDoe@gmail.com',
            'password' => bcrypt('secret'),
            'is_verified' => 1,
            'verification_token' =>null ,
            'remember_token' => str_random(40),
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
        [
            'fname' => 'Cade',
            'lname' => 'Doe',
            'contact' => '09158547791',
            'facebook' => '/sample',
            'twitter' => '/sample',
            'gplus' => null,
            'address' => 'Imus,Cavite',
            'email' =>'CadeDoe@gmail.com',
            'password' => bcrypt('secret'),
            'is_verified' => 1,
            'verification_token' =>null ,
            'remember_token' => str_random(40),
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
        [
            'fname' => 'Cale',
            'lname' => 'Doe',
            'contact' => '09158547791',
            'facebook' => '/sample',
            'twitter' => '/sample',
            'gplus' => null,
            'address' => 'Imus,Cavite',
            'email' =>'CaleDoe@gmail.com',
            'password' => bcrypt('secret'),
            'is_verified' => 1,
            'verification_token' =>null ,
            'remember_token' => str_random(40),
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
        [
            'fname' => 'Cree',
            'lname' => 'Doe',
            'contact' => '09158547791',
            'facebook' => '/sample',
            'twitter' => '/sample',
            'gplus' => null,
            'address' => 'Imus,Cavite',
            'email' =>'CreeDoe@gmail.com',
            'password' => bcrypt('secret'),
            'is_verified' => 1,
            'verification_token' =>null ,
            'remember_token' => str_random(40),
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
        [
            'fname' => 'Courage',
            'lname' => 'Doe',
            'contact' => '09158547791',
            'facebook' => '/sample',
            'twitter' => '/sample',
            'gplus' => null,
            'address' => 'Imus,Cavite',
            'email' =>'CourageDoe@gmail.com',
            'password' => bcrypt('secret'),
            'is_verified' => 1,
            'verification_token' =>null ,
            'remember_token' => str_random(40),
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
        [
            'fname' => 'Carlyle',
            'lname' => 'Doe',
            'contact' => '09158547791',
            'facebook' => '/sample',
            'twitter' => '/sample',
            'gplus' => null ,
            'address' => 'Imus,Cavite',
            'email' =>'CarlyleDoe@gmail.com',
            'password' => bcrypt('secret'),
            'is_verified' => 1,
            'verification_token' =>null ,
            'remember_token' => str_random(40),
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
      [
            'fname' => 'Coltrane',
            'lname' => 'Doe',
            'contact' => '09158547791',
            'facebook' => '/sample',
            'twitter' => '/sample',
            'gplus' => null ,
            'address' => 'Imus,Cavite',
            'email' =>'ColtraneDoe@gmail.com',
            'password' => bcrypt('secret'),
            'is_verified' => 1,
            'verification_token' =>null ,
            'remember_token' => str_random(40),
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
      [
            'fname' => 'Clyde',
            'lname' => 'Doe',
            'contact' => '09158547791',
            'facebook' => '/sample',
            'twitter' => '/sample',
            'gplus' => null ,
            'address' => 'Imus,Cavite',
            'email' =>'ClydeDoe@gmail.com',
            'password' => bcrypt('secret'),
            'is_verified' => 1,
            'verification_token' =>null ,
            'remember_token' => str_random(40),
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
      [
            'fname' => 'Corrie',
            'lname' => 'Doe',
            'contact' => '09158547791',
            'facebook' => '/sample',
            'twitter' => '/sample',
            'gplus' => null,
            'address' => 'Imus,Cavite',
            'email' =>'CorrieDoe@gmail.com',
            'password' => bcrypt('secret'),
            'is_verified' => 1,
            'verification_token' =>null ,
            'remember_token' => str_random(40),
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
      [
            'fname' => 'Cruise',
            'lname' => 'Doe',
            'contact' => '09158547791',
            'facebook' => '/sample',
            'twitter' => '/sample',
            'gplus' => null,
            'address' => 'Imus,Cavite',
            'email' =>'CruiseDoe@gmail.com',
            'password' => bcrypt('secret'),
            'is_verified' => 1,
            'verification_token' =>null ,
            'remember_token' => str_random(40),
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
      [
            'fname' => 'Clarence',
            'lname' => 'Doe',
            'contact' => '09158547791',
            'facebook' => '/sample',
            'twitter' => '/sample',
            'gplus' => null ,
            'address' => 'Imus,Cavite',
            'email' =>'ClarenceDoe@gmail.com',
            'password' => bcrypt('secret'),
            'is_verified' => 1,
            'verification_token' =>null ,
            'remember_token' => str_random(40),
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
    [
            'fname' => 'Clive',
            'lname' => 'Doe',
            'contact' => '09158547791',
            'facebook' => '/sample',
            'twitter' => '/sample',
            'gplus' => null ,
            'address' => 'Imus,Cavite',
            'email' =>'CliveDoe@gmail.com',
            'password' => bcrypt('secret'),
            'is_verified' => 1,
            'verification_token' =>null ,
            'remember_token' => str_random(40),
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
    [
            'fname' => 'Claire',
            'lname' => 'Doe',
            'contact' => '09158547791',
            'facebook' => '/sample',
            'twitter' => '/sample',
            'gplus' => null ,
            'address' => 'Imus,Cavite' ,
            'email' =>'ClaireDoe@gmail.com',
            'password' => bcrypt('secret'),
            'is_verified' => 1,
            'verification_token' =>null ,
            'remember_token' => str_random(40),
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
      [
            'fname' => 'Channe',
            'lname' => 'Doe',
            'contact' => '09158547791',
            'facebook' => '/sample',
            'twitter' => '/sample',
            'gplus' => null ,
            'address' => 'Imus,Cavite',
            'email' =>'ChanneDoe@gmail.com',
            'password' => bcrypt('secret'),
            'is_verified' => 1,
            'verification_token' =>null ,
            'remember_token' => str_random(40),
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
      [
            'fname' => 'Codie',
            'lname' => 'Doe',
            'contact' => '09158547791',
            'facebook' => '/sample',
            'twitter' => '/sample',
            'gplus' => null ,
            'address' => 'Imus,Cavite',
            'email' =>'CodieDoe@gmail.com',
            'password' => bcrypt('secret'),
            'is_verified' => 1,
            'verification_token' =>null ,
            'remember_token' => str_random(40),
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
      [
            'fname' => 'Chaz',
            'lname' => 'Doe',
            'contact' => '09158547791',
            'facebook' => '/sample',
            'twitter' => '/sample',
            'gplus' => null,
            'address' =>  'General Trias',
            'email' =>'ChazDoe@gmail.com',
            'password' => bcrypt('secret'),
            'is_verified' => 1,
            'verification_token' =>null ,
            'remember_token' => str_random(40),
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
      [
            'fname' => 'Chance',
            'lname' => 'Doe',
            'contact' => '09158547791',
            'facebook' => '/sample',
            'twitter' => '/sample',
            'gplus' => null ,
            'address' =>  'General Trias',
            'email' =>'ChanceDoe@gmail.com',
            'password' => bcrypt('secret'),
            'is_verified' => 1,
            'verification_token' =>null ,
            'remember_token' => str_random(40),
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
      [
            'fname' => 'Charlie',
            'lname' => 'Doe',
            'contact' => '09158547791',
            'facebook' => '/sample',
            'twitter' => '/sample',
            'gplus' => null ,
            'address' =>  'General Trias',
            'email' =>'CharlieDoe@gmail.com',
            'password' => bcrypt('secret'),
            'is_verified' => 1,
            'verification_token' =>null ,
            'remember_token' => str_random(40),
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
      [
            'fname' => 'Clayborne',
            'lname' => 'Doe',
            'contact' => '09158547791',
            'facebook' => '/sample',
            'twitter' => '/sample',
            'gplus' => null ,
            'address' =>  'General Trias',
            'email' =>'ClayborneDoe@gmail.com',
            'password' => bcrypt('secret'),
            'is_verified' => 1,
            'verification_token' =>null ,
            'remember_token' => str_random(40),
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
      [
            'fname' => 'Christie',
            'lname' => 'Owens',
            'contact' => '09158547791',
            'facebook' => '/sample',
            'twitter' => '/sample',
            'gplus' => null ,
            'address' =>  'General Trias',
            'email' =>'ChristieDoe@gmail.com',
            'password' => bcrypt('secret'),
            'is_verified' => 1,
            'verification_token' =>null ,
            'remember_token' => str_random(40),
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
      [
            'fname' => 'Cyrene',
            'lname' => 'Owens',
            'contact' => '09158547791',
            'facebook' => '/sample',
            'twitter' => '/sample',
            'gplus' => null,
            'address' =>  'General Trias',
            'email' =>'CyreneDoe@gmail.com',
            'password' => bcrypt('secret'),
            'is_verified' => 1,
            'verification_token' =>null ,
            'remember_token' => str_random(40),
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
      [
            'fname' => 'Clement',
            'lname' => 'Owens',
            'contact' => '09158547791',
            'facebook' => '/sample',
            'twitter' => '/sample',
            'gplus' => null ,
            'address' =>  'General Trias',
            'email' =>'ClementDoe@gmail.com',
            'password' => bcrypt('secret'),
            'is_verified' => 1,
            'verification_token' =>null ,
            'remember_token' => str_random(40),
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
          [
            'fname' => 'Hope',
            'lname' => 'Owens',
            'contact' => '09158547791',
            'facebook' => '/sample',
            'twitter' => '/sample',
            'gplus' => null,
            'address' =>  'General Trias',
            'email' =>'HopeDoe@gmail.com',
            'password' => bcrypt('secret'),
            'is_verified' => 1,
            'verification_token' =>null ,
            'remember_token' => str_random(40),
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
            [
            'fname' => 'Chancellor',
            'lname' => 'Owens',
            'contact' => '09158547791',
            'facebook' => '/sample',
            'twitter' => '/sample',
            'gplus' => null ,
            'address' =>  'General Trias',
            'email' =>'ChancellorDoe@gmail.com',
            'password' => bcrypt('secret'),
            'is_verified' => 1,
            'verification_token' =>null ,
            'remember_token' => str_random(40),
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
            [
            'fname' => 'Claudia',
            'lname' => 'Owens',
            'contact' => '09158547791',
            'facebook' => '/sample',
            'twitter' => '/sample',
            'gplus' => null ,
            'address' =>  'General Trias',
            'email' =>'ClaudiaDoe@gmail.com',
            'password' => bcrypt('secret'),
            'is_verified' => 1,
            'verification_token' =>null ,
            'remember_token' => str_random(40),
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
            [
            'fname' => 'Christian',
            'lname' => 'Owens',
            'contact' => '09158547791',
            'facebook' => '/sample',
            'twitter' => '/sample',
            'gplus' => null ,
            'address' =>  'General Trias',
            'email' =>'ChristianDoe@gmail.com',
            'password' => bcrypt('secret'),
            'is_verified' => 1,
            'verification_token' =>null ,
            'remember_token' => str_random(40),
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
            [
            'fname' => 'Alexia',
            'lname' => 'Owens',
            'contact' => '09158547791',
            'facebook' => '/sample',
            'twitter' => '/sample' ,
            'gplus' => null ,
            'address' =>  'General Trias',
            'email' =>'AlexiaOwens@gmail.com',
            'password' => bcrypt('secret'),
            'is_verified' => 1,
            'verification_token' =>null ,
            'remember_token' => str_random(40),
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
            [
            'fname' => 'Amelia',
            'lname' => 'Owens',
            'contact' => '09158547791',
            'facebook' => '/sample',
            'twitter' => '/sample',
            'gplus' => null ,
            'address' =>  'General Trias',
            'email' =>'AmeliaOwens@gmail.com',
            'password' => bcrypt('secret'),
            'is_verified' => 1,
            'verification_token' =>null ,
            'remember_token' => str_random(40),
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
            [
            'fname' => 'Annabel',
            'lname' => 'Owens',
            'contact' => '09158547791',
            'facebook' => '/sample',
            'twitter' => '/sample',
            'gplus' => null ,
            'address' =>  'Dasmariñas',
            'email' =>'AnnabelOwens@gmail.com',
            'password' => bcrypt('secret'),
            'is_verified' => 1,
            'verification_token' =>null ,
            'remember_token' => str_random(40),
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
              [
            'fname' => 'Aishah',
            'lname' => 'Owens',
            'contact' => '09158547791',
            'facebook' => '/sample',
            'twitter' => '/sample',
            'gplus' => null,
            'address' =>  'General Trias',
            'email' =>'AishahOwens@gmail.com',
            'password' => bcrypt('secret'),
            'is_verified' => 1,
            'verification_token' =>null ,
            'remember_token' => str_random(40),
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
              [
            'fname' => 'Annabelle',
            'lname' => 'Owens',
            'contact' => '09158547791',
            'facebook' => '/sample',
            'twitter' => '/sample',
            'gplus' => null ,
            'address' =>  'Dasmañas',
            'email' =>'AnnabelleOwens@gmail.com',
            'password' => bcrypt('secret'),
            'is_verified' => 1,
            'verification_token' =>null ,
            'remember_token' => str_random(40),
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
                [
            'fname' => 'Alek',
            'lname' => 'Owens',
            'contact' => '09158547791',
            'facebook' => '/sample',
            'twitter' => '/sample',
            'gplus' => null,
            'address' =>  'General Trias',
            'email' =>'AlekOwens@gmail.com',
            'password' => bcrypt('secret'),
            'is_verified' => 1,
            'verification_token' =>null ,
            'remember_token' => str_random(40),
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
    [
            'fname' => 'Abigail',
            'lname' => 'Owens',
            'contact' => '09158547791',
            'facebook' => '/sample',
            'twitter' => '/sample',
            'gplus' => null ,
            'address' =>  'General Trias',
            'email' =>'AbigailOwens@gmail.com',
            'password' => bcrypt('secret'),
            'is_verified' => 1,
            'verification_token' =>null ,
            'remember_token' => str_random(40),
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
            [
            'fname' => 'Alma',
            'lname' => 'Owens',
            'contact' => '09158547791',
            'facebook' => '/sample',
            'twitter' => '/sample',
            'gplus' => null ,
            'address' =>  'General Trias',
            'email' =>'AlmaOwens@gmail.com',
            'password' => bcrypt('secret'),
            'is_verified' => 1,
            'verification_token' =>null ,
            'remember_token' => str_random(40),
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
            [
            'fname' => 'Ada',
            'lname' => 'Owens',
            'contact' => '09158547791',
            'facebook' => '/sample',
            'twitter' => '/sample',
            'gplus' => null ,
            'address' =>  'General Trias',
            'email' =>'AdaOwens@gmail.com',
            'password' => bcrypt('secret'),
            'is_verified' => 1,
            'verification_token' =>null ,
            'remember_token' => str_random(40),
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
            [
            'fname' => 'Angela',
            'lname' => 'Owens',
            'contact' => '09158547791',
            'facebook' => '/sample',
            'twitter' => '/sample',
            'gplus' => null ,
            'address' =>  'General Trias',
            'email' =>'AngelaOwens@gmail.com',
            'password' => bcrypt('secret'),
            'is_verified' => 1,
            'verification_token' =>null ,
            'remember_token' => str_random(40),
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
            [
            'fname' => 'Angel',
            'lname' => 'Owens',
            'contact' => '09158547791',
            'facebook' => '/sample',
            'twitter' => '/sample',
            'gplus' => null ,
            'address' =>  'General Trias',
            'email' =>'AngelOwens@gmail.com',
            'password' => bcrypt('secret'),
            'is_verified' => 1,
            'verification_token' =>null ,
            'remember_token' => str_random(40),
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
            [
            'fname' => 'Angelica',
            'lname' => 'Owens',
            'contact' => '09158547791',
            'facebook' => '/sample',
            'twitter' => '/sample',
            'gplus' => null ,
            'address' =>  'General Trias',
            'email' =>'AngelicaOwens@gmail.com',
            'password' => bcrypt('secret'),
            'is_verified' => 1,
            'verification_token' =>null ,
            'remember_token' => str_random(40),
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
            [
            'fname' => 'Ayah',
            'lname' => 'Owens',
            'contact' => '09158547791',
            'facebook' => '/sample',
            'twitter' => '/sample',
            'gplus' => null ,
            'address' =>  'General Trias',
            'email' =>'AyahOwens@gmail.com',
            'password' => bcrypt('secret'),
            'is_verified' => 1,
            'verification_token' =>null ,
            'remember_token' => str_random(40),
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
            [
            'fname' => 'Ayla',
            'lname' => 'Owens',
            'contact' => '09158547791',
            'facebook' => '/sample',
            'twitter' => '/sample',
            'gplus' => null ,
            'address' =>  'General Trias',
            'email' =>'AylaOwens@gmail.com',
            'password' => bcrypt('secret'),
            'is_verified' => 1,
            'verification_token' =>null ,
            'remember_token' => str_random(40),
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ]
    );
    }}
    }
