<?php

use Illuminate\Database\Seeder;

class VenuesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      
        DB::table('venues')->insert([[
            'id' => 11,
            'name' => 'Republic of Cavite Restaurant',
            'address' => 'City Hall Road ,Trece Martires, Cavite',
            'contact_person' => 'Cecille',
            'contact'=> '046-4190214',
            'price' => 25000,
            'file' => 'republic of cavite resto.jpg', 
            'capacity' => 70,
            'is_active' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
        [
            'id' => 12,
            'name' => 'Stat Events and Trends',
            'address' => 'EAM Building Barangay, Anabu 1D Aguinaldo Highway 2nd Floor Imus Cavite',
            'contact_person' => 'Althea',
            'contact'=> '09176921168',
            'price' => 20000,
            'file' => 'stat event trends.jpg', 
            'capacity' => 50,
            'is_active' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
		[
            'id' => 13,
            'name' => 'The Monochrome',
            'address' => 'Venado. Santa Rosa City, Laguna',
            'contact_person' => 'Wilnel',
            'contact'=> '02-8464334',
            'price' => 55000,
            'file' => 'monochrome.jpg',
            'capacity' => 100,
            'is_active' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
		
		[
            'id' => 14,
            'name' => 'The Living Room Bar',
            'address' => '7610 Chestnut Street Amrcelo Green Village Paranaque, 1715 Metro Manila Paranaque City',
            'contact_person' => 'Edwin',
            'contact'=> '02-7751566',
            'price' => 15000,
            'file' => 'livingroom.jpg',
            'capacity' => 40,
            'is_active' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
		
		[
            'id' => 15,
            'name' => 'Tagaytay Wedding Café',
            'address' => 'Tagaytay - Amadeo Road, Barangay Salaban Terrace Hill Resort, Amadeo, Cavite',
            'contact_person' => 'Jason',
            'contact'=> '046-4835307',
            'price' => 80,000,
            'file' =>'tagaytayweds.jpg', 
            'capacity' => 120,
            'is_active' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
		
		[
            'id' => 16,
            'name' => 'Palacio De Maynila',
            'address' => '1809-1813 MH Del Pilar St. Manila City',
            'contact_person' => 'Mary',
            'contact'=> '02-5247606',
            'price' => 250000,
            'file' =>' palacio.jpg', 
            'capacity' => 400,
            'is_active' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
		
		[
            'id' => 17,
            'name' => 'Plaza San Luis Complex',
            'address' => 'Geeral Luna Street cor Real St., Intramuros Manila, Metrol Manila',
            'contact_person' => 'Sergio',
            'contact'=> '02-5274084',
            'price' => 70000,
            'file' => 'plazasl.jpg', 
            'capacity' => 150,
            'is_active' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
		
		[
            'id' => 18,
            'name' => 'The Pergola',
            'address' => 'Sen. Gil J. Puyat Avenue',
            'contact_person' => 'Andrei',
            'contact'=> '02-6171749',
            'price' => 90000,
            'file' => 'pergola.jpg', 
            'capacity' => 150,
            'is_active' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
		
		[
            'id' => 19,
            'name' => 'The Farm Green and Saddle Resort',
            'address' => 'Amuntay Road, Dasmarinas, 4114 Cavite',
            'contact_person' => 'Mr. Sid',
            'contact'=> '09328632807',
            'price' => 26000,
            'file' => 'farmgreen.jpg',
            'capacity' => 400,
            'is_active' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
		
		[
            'id' => 20,
            'name' => 'Chardan Events Place',
            'address' => '4103, 841 Emilio Aguinaldo Hwy, Anabu 1-D, Imus, Cavite',
            'contact_person' => 'Mrs. Marya',
            'contact'=> '(046)6862441',
            'price' => 76000,
            'file' => 'chardan.png',
            'capacity' => 130,
            'is_active' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],

		[   
            'id' => 21,
            'name' => 'The Paradiso Terrestre',
            'address' => '1, 170933 National Road, Molino Highway, Molino IV, Cavite City',
            'contact_person' => 'Mr. Janzon',
            'contact'=> '(02)5844127',
            'price' => 190000,
            'file' =>' paradiso.jpg',
            'capacity' => 300,
            'is_active' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
		
		[
            'id' => 22,
            'name' => 'Casa Ladrillo',
            'address' => 'Daang Hari Road, Imus Cavite',
            'contact_person' => 'Mrs. Diaz',
            'contact'=> '09178209211',
            'price' => 325000,
            'file' =>' casa ladrillosa.jpg',
            'capacity' => 500,
            'is_active' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
		
		[
            'id' => 23,
            'name' => 'Satis Place Party Venue',
            'address' => 'Avenida Rizal, Molino 5, Bacoor, Cavite',
            'contact_person' => 'Mr. Tolentino',
            'contact'=> '(046)4770580',
            'price' => 80000,
            'file' => 'satis place venue.jpg',
            'capacity' => 200,
            'is_active' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
		
		[
            'id' => 24,
            'name' => 'Hannahs Garden Event Place',
            'address' => 'Silang Road, Calamba, Laguna',
            'contact_person' => 'Mrs. Roxas',
            'contact'=> '09778049156',
            'price' => 90000,
            'file' =>' hannahs.jpg',
            'capacity' => 200,
            'is_active' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
		
		[
            'id' => 25,
            'name' => 'Torreno Resort And Pavillion',
            'address' => 'Dagohoy St. Extenson Bahayang Pag-asa Phase 1, Molino, Bacoor, Cavite',
            'contact_person' => 'Kenneth',
            'contact'=> '(046)4167517',
            'price' => 50000,
            'file' => 'torreno resort.jpg',
            'capacity' => 100,
            'is_active' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
		
		[
            'id' => 26,
            'name' => 'Patio Buendia',
            'address' => 'C.M De Los Reyes Ave, Amadeo, 4119 Cavite',
            'contact_person' => 'Event Planner',
            'contact'=> '(046) 6868066',
            'price' => 55000,
            'file' =>'patio bbb.jpg',
            'capacity' => 100,
            'is_active' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
		
		[
            'id' => 27,
            'name' => 'Aminsana Tagaytay Events Place',
            'address' => 'A. Mabini St., Barangay Cinco, Amadeo, Cavite',
            'contact_person' => 'Supervisor',
            'contact'=> '(02)4014825',
            'price' => 175000,
            'file' => 'aminsana.png',
            'capacity' => 400,
            'is_active' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
		
		[
            'id' => 28,
            'name' => 'S. Cassandras Place Events Venue Resort',
            'address' => 'San Francisco Road, Binan, Laguna',
            'contact_person' => 'Dishwasher',
            'contact'=> '09178985113',
            'price' => 34000,
            'file' => 'cassandras place.jpg',
            'capacity' => 40,
            'is_active' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
		
		[
            'id' => 29,
            'name' => 'Takahara Hotel & Events Place',
            'address' => 'San Antonio, San Pedro Laguna',
            'contact_person' => 'Server',
            'contact'=> '(02)9840654',
            'price' => 140000,
            'file' => 'takahara.jpg',
            'capacity' => 200,
            'is_active' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
		
		[
            'id' => 30,
            'name' => 'South Country Garden',
            'address' => 'Block 4 Lot 1 Panorama Ville, barangay Dita, Santa Rosa, Laguna',
            'contact_person' => 'Event Planner',
            'contact'=> '09176733017',
            'price' => 100000,
            'file' => 'south country.png',
            'capacity' => 150,
            'is_active' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
		
		[
            'id' => 31,
            'name' => 'C-Summit Events Place',
            'address' => 'Jp Rizal St, Calamaba, Laguna',
            'contact_person' => 'Server',
            'contact'=> '09283786021',
            'price' => 50000,
            'file' => 'csummit.jpg',
            'capacity' => 80,
            'is_active' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
		
		[
            'id' => 32,
            'name' => 'Zion Events Place',
            'address' => 'San Antonio, San Pedro  Laguna',
            'contact_person' => 'Dishwasher',
            'contact'=> '09219615157',
            'price' => 130,000,
            'file' => 'zion.jpg',
            'capacity' => 200,
            'is_active' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
		
		[
            'id' => 33,
            'name' => 'Lakehouse San Pablo Events Place',
            'address' => '645 Sabang Road, Concepcion, San Pablo City, Laguna',
            'contact_person' => 'Setup Crew',
            'contact'=> '(046)5730115',
            'price' => 50000,
            'file' => 'lakehouse.jpg',
            'capacity' => 80,
            'is_active' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
		
		[
            'id' => 34,
            'name' => 'Patio Fernando',
            'address' => '41 Magsaysay Road San Antonio San Pedro, Laguna',
            'contact_person' => 'Dishwasher',
            'contact'=> '09988898048',
            'price' => 70000,
            'file' => 'patio fernandos.jpg',
            'capacity' => 80,
            'is_active' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ],
		
		[
            'id' => 35,
            'name' => 'South Yard Events Place',
            'address' => 'National Highway, Santa Cruz, Laguna',
            'contact_person' => 'Mr. Roman',
            'contact'=> '0906293210',
            'price' =>  100000,
            'file' =>'southy.jpg',
            'capacity' => 150,
            'is_active' => 1,
            'created_at' => date("Y-m-d H:i:s"),
            'updated_at' => date("Y-m-d H:i:s"),
        ]]
    );
    }
}
